/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ulb.lisa.infoh400.labs2022.view;

import java.awt.event.MouseEvent;
import java.util.ArrayList;
import java.util.List;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import ulb.lisa.infoh400.labs2022.controller.PatientJpaController;
import ulb.lisa.infoh400.labs2022.model.Doctor;
import ulb.lisa.infoh400.labs2022.model.Patient;

/**
 *
 * @author renau
 */
public class DoctorWindow extends javax.swing.JFrame {

    private final EntityManagerFactory emfac = Persistence.createEntityManagerFactory("infoh400_PU");
    private final PatientJpaController patientCtrl = new PatientJpaController(emfac);
    private List<Patient> myPat;
    
    
    public DoctorWindow() {
        initComponents();
        myPat = new ArrayList <Patient>();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Hi_label = new javax.swing.JLabel();
        rschPatientLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        rschPatientList = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        yourPatientList = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        patientInfoTextArea = new javax.swing.JTextArea();
        yourPatientLabel = new javax.swing.JLabel();
        refreshButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        Hi_label.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Hi_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Hi_label.setText("Hi Doc !");

        rschPatientLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rschPatientLabel.setText("Research Patient");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Patient Information");

        rschPatientList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { " " };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        rschPatientList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rschPatientListMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(rschPatientList);

        yourPatientList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                yourPatientListMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(yourPatientList);

        patientInfoTextArea.setColumns(20);
        patientInfoTextArea.setRows(5);
        jScrollPane3.setViewportView(patientInfoTextArea);

        yourPatientLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        yourPatientLabel.setText("Your Patient");

        refreshButton.setText("Refresh");
        refreshButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Hi_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rschPatientLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                            .addComponent(yourPatientLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(refreshButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Hi_label, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rschPatientLabel)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(refreshButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(yourPatientLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE))
                    .addComponent(jScrollPane3))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void refreshButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshButtonActionPerformed
        refreshPatientList();
    }//GEN-LAST:event_refreshButtonActionPerformed

    private void yourPatientListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_yourPatientListMouseClicked
        String out = "";
        
        if (evt.getClickCount() == 2 && evt.getButton() == MouseEvent.BUTTON1 && yourPatientList.getSelectedIndex() >= 0) {
            
            EntityListModel model = (EntityListModel) yourPatientList.getModel();

            Patient selected = (Patient) model.getList().get(yourPatientList.getSelectedIndex());
            
            String phone = selected.getPhonenumber();
            String status = selected.getStatus();
            Integer id = selected.getIdpatient();
            int nbrImage = selected.getImageList().size();
            
            out = "Phone number : " + phone + "\n"
                + "Status : " +status + "\n"
                + "Id patient : " + id.toString() + "\n"
                + "Available image(s) : " + nbrImage + "\n";
            
         }
        patientInfoTextArea.setText(out);
    }//GEN-LAST:event_yourPatientListMouseClicked

    private void rschPatientListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rschPatientListMouseClicked
        String out = "";
        
        if (evt.getClickCount() == 2 && evt.getButton() == MouseEvent.BUTTON1 && rschPatientList.getSelectedIndex() >= 0) {
            //System.out.println("Im CLIKECD");
            EntityListModel model = (EntityListModel) rschPatientList.getModel();

            Patient selected = (Patient) model.getList().get(rschPatientList.getSelectedIndex());

            int patid = selected.getIdpatient();

            refreshYourPatientList(patid);
            
         }
        patientInfoTextArea.setText(out);
    }//GEN-LAST:event_rschPatientListMouseClicked

    private void refreshYourPatientList(int patId) {
        Patient pat = patientCtrl.findPatient(patId);
        if (!myPat.contains(pat)){
            myPat.add(pat);
            //System.out.println("Im OK");
        }
        //System.out.println("Im OK bis");
        EntityListModel<Doctor> model = new EntityListModel(myPat);
        yourPatientList.setModel(model);
    }
    
    private void refreshPatientList(){
        List patients = patientCtrl.findPatientEntities();
        EntityListModel<Patient> model = new EntityListModel(patients);
        rschPatientList.setModel(model);
        //tempo pour test
        //yourPatientList.setModel(model);
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Hi_label;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea patientInfoTextArea;
    private javax.swing.JButton refreshButton;
    private javax.swing.JLabel rschPatientLabel;
    private javax.swing.JList<String> rschPatientList;
    private javax.swing.JLabel yourPatientLabel;
    private javax.swing.JList<String> yourPatientList;
    // End of variables declaration//GEN-END:variables
}
